### ISSUE TITLE
Android集成2.1.7运行报错“Didn't find class "com.umeng.message.provider.MessageProvider"”

### ISSUE THREAD

**Issue by TennisAndy** [zileyuan/umeng_analytics_push#51]
更新flutter2.1.7后，编译打包正常，运行报错：
2022-08-30 16:36:30.447 20073-20073/com.fdage.turn.dual E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fdage.turn.dual, PID: 20073
    java.lang.RuntimeException: Unable to get provider com.umeng.message.provider.MessageProvider: java.lang.ClassNotFoundException: Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList[[zip file "/data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/base.apk"],nativeLibraryDirectories=[/data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/lib/arm64, /data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:7828)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7364)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7250)
        at android.app.ActivityThread.access$1600(ActivityThread.java:293)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:263)
        at android.app.ActivityThread.main(ActivityThread.java:8283)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.umeng.message.provider.MessageProvider" on path: DexPathList[[zip file "/data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/base.apk"],nativeLibraryDirectories=[/data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/lib/arm64, /data/app/~~htfzxfUjJJovPFZXlJSXlA==/com.fdage.turn.dual-fDYakKhfFLuTpZO76mqiUA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /vendor/lib64, /odm/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at androidx.core.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:67)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7812)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7364) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7250) 
        at android.app.ActivityThread.access$1600(ActivityThread.java:293) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2151) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:263) 
        at android.app.ActivityThread.main(ActivityThread.java:8283) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)

**Comment by zileyuan** [comment]
请升级 2.1.8
